MODKBEKBJ-614 Upgrade to RAML Module Builder 33.2.4
folio-org/mod-kb-ebsco-java pull request #391
Opened 2022-01-21 12:39 UTC by ALiemeshka

Update to the latest RMB 33.2.* release.

See details: https://github.com/folio-org/raml-module-builder/blob/master/doc/upgrading.md

2022-01-21 14:40 UTC, psmagin requested changes

2022-01-21 14:40 UTC, psmagin commented on pom.xml
> +    <folio-service-tools.version>1.7.2</folio-service-tools.version>
Please update to SNAPSHOT versions

2022-01-24 11:49 UTC, psmagin approved these changes

2022-01-24 12:42 UTC, Shans-Kaluhin approved these changes

2022-01-24 12:47 UTC, merged