modkbekbj-622 Remove parameters from POST request of '/eholdings/kb-credentials
folio-org/mod-kb-ebsco-java pull request #402
Opened 2022-04-07 09:44 UTC by DieHardJava

## Purpose
Remove user-related fields from POST api call because user data is queried from mod-users, not from database.

## Approach
remove "firstName", "lastName", "patronGroup", "userName" from api;
update repository interaction (save only kb_id to user_id relation).

2022-04-14 08:39 UTC, psmagin requested changes

2022-04-14 08:39 UTC, psmagin commented on ramls/types/assignedUsers/assignedUserPutRequest.json
> -  "title": "PUT Request To Assigned Users Collection Schema",
I think we can remove PUT endpoint for assigned users. It will never be used

2022-04-14 08:39 UTC, psmagin commented on src/main/java/org/folio/rest/converter/assignedusers/AssignedUserCollectionItemConverter.java
> +  public static class toAssignedUserId implements Converter<DbAssignedUser, AssignedUserId> {
```suggestion
  public static class ToAssignedUserId implements Converter<DbAssignedUser, AssignedUserId> {
```

2022-04-14 11:54 UTC, psmagin approved these changes

2022-04-15 15:05 UTC, Igor-Gorchakov approved these changes

2022-04-15 15:07 UTC, Shans-Kaluhin approved these changes

2022-04-15 18:27 UTC, merged