preview of modkbekbj-621
folio-org/mod-kb-ebsco-java pull request #403
Opened 2022-04-11 06:31 UTC by DieHardJava

## Purpose
Rework GET request for '/kb-credentials/{kb-credentials-id}/users'

## Approach
get assigned users from db (only user ids by kb_credentials_id);
query users info from `mod-users` for assigned users using "/users" api and cql (Check the max possible amount of users we can query this way and implement batches so if for example we have 200 assigned users in db and the limit is 50 then we should execute 4 queries with 50 users each and compose results then);
query groups info using "/groups" api of  `mod-users`;
aggregate received info and pass as response.

2022-04-11 07:42 UTC, psmagin requested changes

2022-04-11 07:42 UTC, psmagin commented on src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
> +    }));
You should request a collection of users in one request. For this purpose use CQL query like:
`query=id=<id1> or id=<id2> or ....`
Please remember that url and response body have limitations, so request users in batches.

2022-04-11 07:42 UTC, psmagin commented on src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
> +    }));
Same for groups, use cql query

2022-04-11 07:42 UTC, psmagin commented on src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
> +          return g.add(usersLookUpService.lookUpGroup(new OkapiParams(okapiHeaders)).get());
You shouldn't finalize futures. Just combine futures to get the expected result.

2022-04-11 07:42 UTC, psmagin commented on src/main/java/org/folio/service/assignedusers/AssignedUsersServiceImpl.java
> +          assignedUser.getAttributes().setPatronGroup(groupsList.get(c.incrementAndGet()).getGroup())));
You can't be sure that the groups' collection has the same side or in the same order. Use group id to identify which group name to use.

2022-04-11 07:42 UTC, psmagin commented on src/main/java/org/folio/service/users/UsersLookUpService.java
> +      builder.expirationOffsetInDays(group.getInteger("expirationOffsetInDays"));
Why do you need these fields? If you don't use them, just not map them.

2022-04-13 11:10 UTC, psmagin approved these changes

2022-04-14 17:14 UTC, viacheslavkol approved these changes

2022-04-15 06:10 UTC, merged